### ISSUE TITLE
Image not listed after adding via Curl Script

### ISSUE THREAD

**Issue by GeSern** [LayeredInsight/scan-api-example-python#16]
I successfully deleted an image using the curl script below:
curl  -H Authorization:$LI_API_KEY -X DELETE $LI_API_HOST/Images/IM156fba7501a6817f70f158a512f5d2204f43a33d2106756f5fc1860d351879f0586ec199e4d02a31

however I was trying to add back the same image with the script below but could not list that same image when I ran the "li_list_images" command
curl -H Authorization:$LI_API_KEY -X ADD $LI_API_HOST/Images/registry.gear.ge.com/layered-insight-beta/lidatest3:latest

is there something that I am missing here?

**Comment by oberg-s** [comment]
> `curl -H Authorization:$LI_API_KEY -X ADD $LI_API_HOST/Images/registry.gear.ge.com/layered-insight-beta/lidatest3:latest`

The REST endpoint to add an image requires the image name in the request body.  The api does not support passing the name as part of the URL path.

api doc:
https://openapi-scan.layeredinsight.net/#/Images/addImage

request body example:
```
{
  "Name": "myregistry:port/namespace/image:tag"
}
```

curl example:
`curl -H Authorization:${LI_API_KEY} -X POST ${LI_API_HOST}/Images -d '{"Name": "myregistry:port/namespace/image:tag"}'`

python example:
https://github.com/LayeredInsight/scan-api-example-python/blob/master/li_add_image

**Comment by oberg-s** [comment]
> curl example:
> `curl -H Authorization:${LI_API_KEY} -X POST ${LI_API_HOST}/Image -d '{"Name": "myregistry:port/namespace/image:tag"}'`

Correction, `Images` is the endpoint, not `Image`.

curl example:
`curl -H Authorization:${LI_API_KEY} -X POST ${LI_API_HOST}/Images -d '{"Name": "myregistry:port/namespace/image:tag"}'`
